sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image"
  - docker build -t cho/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true cho/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react-app2"
  env: "Dockerreactapp2-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-096519238379"
  bucket_path: "docker-react-app2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
