sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image"
  - docker build -t cho/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true cho/docker-react-app npm run test -- --coverage

after_success:
  - echo "test success"
